version: '3.8'
services:
  broker:
   image: eclipse-mosquitto:2.0.14
   ports:
    - 1885:1885
   volumes:
    - ./config:/mosquitto/config
    - ./data:/mosquitto/data
    - ./log:/mosquitto/log
  pub:
    build:
      context: 'sub'
    tty: true
    volumes:
      - ./sub:/src
