version: '3.8'
services:
  broker:
   image: eclipse-mosquitto:2.0.14
   ports:
    - 1884:1884
   volumes:
    - ./config:/mosquitto/config
    - ./data:/mosquitto/data
    - ./log:/mosquitto/log
  pub:
    build:
      context: 'pub'
    tty: true
    volumes:
      - ./pub:/src
