version: '3.8'
services:
  my-queue:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
 
volumes:
  rabbitmq-data:
